### ISSUE TITLE
kalena.go 오류

### ISSUE THREAD

**Issue by baesy0** [lazypic/studygo#3]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/40417084/64307081-eba2b680-cfcf-11e9-8da7-22e36b923bb6.png">

`go run kalena.go`를 쳤는데 위와 같은 오류가 떠요! 자료구조랑 물려있지 않아서 생기는 것 같은데 어떻게 해결해야 하나요?

**Comment by khw7096** [comment]
```
$ go install
$ kalena
```
